development:
  adapter: mysql2
  database: kondate_development
  username: root
  password: ''
  host: localhost

production:
  url: <%= ENV['DATABASE_URL'] %>


test:
  adapter: mysql2
  database: kondate_test
  username: root
  password: ''
  host: localhost
